### ISSUE TITLE
Create app skeleton

### ISSUE THREAD

**Issue by balanza** [cyf-rome-team-thor/dashboard-kanban#5]
We need to bootstrap the application with the skeleton of a React project. Things to do:

- Create an empty react project (maybe with CRA)
- Setup a high-level folder structure (components, containers, utils, etc)
-  Make sure it compiles to a "Hello world" application

**Comment by saeendamghanian** [comment]
done

**Comment by balanza** [comment]
@saeendamghanian what do you mean by done? We expect a PR to be created.

We can discuss folder structure here if you're stuck in decisions

**Comment by balanza** [comment]
For example, common top-level folders for react applications are:

- `components`, where you place all reusable, generic, single-purpose components you'll use in your app. Examples: input forms, button, titles, photo galleries, etc. Such components are often referred as _dumb components_.
- `containers`, where you place components which are bigger, usually a composition of smaller pieces. This category includes pages, sections, etc. Such components are often referred as _smart components_.
- `utils`, stands for utilities, it's a miscellanea of small functions you will need all across the app. Example: date formatting functions, http clients, etc.
- `services`, where you put all modules that interact with third-party api. If and when we'll connect our UI with `cyf-api`, we'll probably create a `/services/cyf-api.js` module.

About _smart-vs-dumb components_, it's a whole subject and it's not required for you to get it now. If you're interested, there's plenty of articles in the web. This is the first result on Google: https://alligator.io/react/smart-dumb-components/

**Comment by saeendamghanian** [comment]
I mean I did it on my machine. But now I think you meant to create one React app and push it to this repo and work on it as a master. Is it correct?

**Comment by saeendamghanian** [comment]
> @saeendamghanian what do you mean by done? We expect a PR to be created.
> 
> We can discuss folder structure here if you're stuck in decisions



> I mean I did it on my machine. But now I think you meant to create one React app and push it to this repo and work on it as a master. Is it correct?
